# Generated by Django 2.0.1 on 2018-01-14 16:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postarticles',
            name='shortInfo',
            field=models.CharField(default='what is this article about', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postarticles',
            name='tags',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='postarticles',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='postarticles',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
